/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DresClientApi);
  }
}(this, function(expect, DresClientApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DresClientApi.ApiEvaluationState();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiEvaluationState', function() {
    it('should create an instance of ApiEvaluationState', function() {
      // uncomment below and update the code to test ApiEvaluationState
      //var instance = new DresClientApi.ApiEvaluationState();
      //expect(instance).to.be.a(DresClientApi.ApiEvaluationState);
    });

    it('should have the property evaluationId (base name: "evaluationId")', function() {
      // uncomment below and update the code to test the property evaluationId
      //var instance = new DresClientApi.ApiEvaluationState();
      //expect(instance).to.be();
    });

    it('should have the property evaluationStatus (base name: "evaluationStatus")', function() {
      // uncomment below and update the code to test the property evaluationStatus
      //var instance = new DresClientApi.ApiEvaluationState();
      //expect(instance).to.be();
    });

    it('should have the property taskId (base name: "taskId")', function() {
      // uncomment below and update the code to test the property taskId
      //var instance = new DresClientApi.ApiEvaluationState();
      //expect(instance).to.be();
    });

    it('should have the property taskStatus (base name: "taskStatus")', function() {
      // uncomment below and update the code to test the property taskStatus
      //var instance = new DresClientApi.ApiEvaluationState();
      //expect(instance).to.be();
    });

    it('should have the property taskTemplateId (base name: "taskTemplateId")', function() {
      // uncomment below and update the code to test the property taskTemplateId
      //var instance = new DresClientApi.ApiEvaluationState();
      //expect(instance).to.be();
    });

    it('should have the property timeLeft (base name: "timeLeft")', function() {
      // uncomment below and update the code to test the property timeLeft
      //var instance = new DresClientApi.ApiEvaluationState();
      //expect(instance).to.be();
    });

    it('should have the property timeElapsed (base name: "timeElapsed")', function() {
      // uncomment below and update the code to test the property timeElapsed
      //var instance = new DresClientApi.ApiEvaluationState();
      //expect(instance).to.be();
    });

  });

}));
