/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DresClientApi);
  }
}(this, function(expect, DresClientApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DresClientApi.ApiEvaluationTemplate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiEvaluationTemplate', function() {
    it('should create an instance of ApiEvaluationTemplate', function() {
      // uncomment below and update the code to test ApiEvaluationTemplate
      //var instance = new DresClientApi.ApiEvaluationTemplate();
      //expect(instance).to.be.a(DresClientApi.ApiEvaluationTemplate);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new DresClientApi.ApiEvaluationTemplate();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new DresClientApi.ApiEvaluationTemplate();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new DresClientApi.ApiEvaluationTemplate();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instance = new DresClientApi.ApiEvaluationTemplate();
      //expect(instance).to.be();
    });

    it('should have the property modified (base name: "modified")', function() {
      // uncomment below and update the code to test the property modified
      //var instance = new DresClientApi.ApiEvaluationTemplate();
      //expect(instance).to.be();
    });

    it('should have the property taskTypes (base name: "taskTypes")', function() {
      // uncomment below and update the code to test the property taskTypes
      //var instance = new DresClientApi.ApiEvaluationTemplate();
      //expect(instance).to.be();
    });

    it('should have the property taskGroups (base name: "taskGroups")', function() {
      // uncomment below and update the code to test the property taskGroups
      //var instance = new DresClientApi.ApiEvaluationTemplate();
      //expect(instance).to.be();
    });

    it('should have the property tasks (base name: "tasks")', function() {
      // uncomment below and update the code to test the property tasks
      //var instance = new DresClientApi.ApiEvaluationTemplate();
      //expect(instance).to.be();
    });

    it('should have the property teams (base name: "teams")', function() {
      // uncomment below and update the code to test the property teams
      //var instance = new DresClientApi.ApiEvaluationTemplate();
      //expect(instance).to.be();
    });

    it('should have the property teamGroups (base name: "teamGroups")', function() {
      // uncomment below and update the code to test the property teamGroups
      //var instance = new DresClientApi.ApiEvaluationTemplate();
      //expect(instance).to.be();
    });

    it('should have the property judges (base name: "judges")', function() {
      // uncomment below and update the code to test the property judges
      //var instance = new DresClientApi.ApiEvaluationTemplate();
      //expect(instance).to.be();
    });

  });

}));
