/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DresClientApi);
  }
}(this, function(expect, DresClientApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DresClientApi.ApiTaskType();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiTaskType', function() {
    it('should create an instance of ApiTaskType', function() {
      // uncomment below and update the code to test ApiTaskType
      //var instance = new DresClientApi.ApiTaskType();
      //expect(instance).to.be.a(DresClientApi.ApiTaskType);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new DresClientApi.ApiTaskType();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instance = new DresClientApi.ApiTaskType();
      //expect(instance).to.be();
    });

    it('should have the property targetOption (base name: "targetOption")', function() {
      // uncomment below and update the code to test the property targetOption
      //var instance = new DresClientApi.ApiTaskType();
      //expect(instance).to.be();
    });

    it('should have the property hintOptions (base name: "hintOptions")', function() {
      // uncomment below and update the code to test the property hintOptions
      //var instance = new DresClientApi.ApiTaskType();
      //expect(instance).to.be();
    });

    it('should have the property submissionOptions (base name: "submissionOptions")', function() {
      // uncomment below and update the code to test the property submissionOptions
      //var instance = new DresClientApi.ApiTaskType();
      //expect(instance).to.be();
    });

    it('should have the property taskOptions (base name: "taskOptions")', function() {
      // uncomment below and update the code to test the property taskOptions
      //var instance = new DresClientApi.ApiTaskType();
      //expect(instance).to.be();
    });

    it('should have the property scoreOption (base name: "scoreOption")', function() {
      // uncomment below and update the code to test the property scoreOption
      //var instance = new DresClientApi.ApiTaskType();
      //expect(instance).to.be();
    });

    it('should have the property configuration (base name: "configuration")', function() {
      // uncomment below and update the code to test the property configuration
      //var instance = new DresClientApi.ApiTaskType();
      //expect(instance).to.be();
    });

  });

}));
