/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DresClientApi);
  }
}(this, function(expect, DresClientApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DresClientApi.DresInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DresInfo', function() {
    it('should create an instance of DresInfo', function() {
      // uncomment below and update the code to test DresInfo
      //var instance = new DresClientApi.DresInfo();
      //expect(instance).to.be.a(DresClientApi.DresInfo);
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new DresClientApi.DresInfo();
      //expect(instance).to.be();
    });

    it('should have the property startTime (base name: "startTime")', function() {
      // uncomment below and update the code to test the property startTime
      //var instance = new DresClientApi.DresInfo();
      //expect(instance).to.be();
    });

    it('should have the property uptime (base name: "uptime")', function() {
      // uncomment below and update the code to test the property uptime
      //var instance = new DresClientApi.DresInfo();
      //expect(instance).to.be();
    });

    it('should have the property os (base name: "os")', function() {
      // uncomment below and update the code to test the property os
      //var instance = new DresClientApi.DresInfo();
      //expect(instance).to.be();
    });

    it('should have the property jvm (base name: "jvm")', function() {
      // uncomment below and update the code to test the property jvm
      //var instance = new DresClientApi.DresInfo();
      //expect(instance).to.be();
    });

    it('should have the property args (base name: "args")', function() {
      // uncomment below and update the code to test the property args
      //var instance = new DresClientApi.DresInfo();
      //expect(instance).to.be();
    });

    it('should have the property cores (base name: "cores")', function() {
      // uncomment below and update the code to test the property cores
      //var instance = new DresClientApi.DresInfo();
      //expect(instance).to.be();
    });

    it('should have the property freeMemory (base name: "freeMemory")', function() {
      // uncomment below and update the code to test the property freeMemory
      //var instance = new DresClientApi.DresInfo();
      //expect(instance).to.be();
    });

    it('should have the property totalMemory (base name: "totalMemory")', function() {
      // uncomment below and update the code to test the property totalMemory
      //var instance = new DresClientApi.DresInfo();
      //expect(instance).to.be();
    });

    it('should have the property load (base name: "load")', function() {
      // uncomment below and update the code to test the property load
      //var instance = new DresClientApi.DresInfo();
      //expect(instance).to.be();
    });

    it('should have the property availableSeverThreads (base name: "availableSeverThreads")', function() {
      // uncomment below and update the code to test the property availableSeverThreads
      //var instance = new DresClientApi.DresInfo();
      //expect(instance).to.be();
    });

  });

}));
