/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DresClientApi);
  }
}(this, function(expect, DresClientApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DresClientApi.EvaluationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EvaluationApi', function() {
    describe('getApiV2EvaluationByEvaluationIdInfo', function() {
      it('should call getApiV2EvaluationByEvaluationIdInfo successfully', function(done) {
        //uncomment below and update the code to test getApiV2EvaluationByEvaluationIdInfo
        //instance.getApiV2EvaluationByEvaluationIdInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiV2EvaluationByEvaluationIdState', function() {
      it('should call getApiV2EvaluationByEvaluationIdState successfully', function(done) {
        //uncomment below and update the code to test getApiV2EvaluationByEvaluationIdState
        //instance.getApiV2EvaluationByEvaluationIdState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiV2EvaluationInfoList', function() {
      it('should call getApiV2EvaluationInfoList successfully', function(done) {
        //uncomment below and update the code to test getApiV2EvaluationInfoList
        //instance.getApiV2EvaluationInfoList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiV2EvaluationStateList', function() {
      it('should call getApiV2EvaluationStateList successfully', function(done) {
        //uncomment below and update the code to test getApiV2EvaluationStateList
        //instance.getApiV2EvaluationStateList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
