/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DresClientApi);
  }
}(this, function(expect, DresClientApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DresClientApi.UserApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserApi', function() {
    describe('deleteApiV2UserByUserId', function() {
      it('should call deleteApiV2UserByUserId successfully', function(done) {
        //uncomment below and update the code to test deleteApiV2UserByUserId
        //instance.deleteApiV2UserByUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiV2Logout', function() {
      it('should call getApiV2Logout successfully', function(done) {
        //uncomment below and update the code to test getApiV2Logout
        //instance.getApiV2Logout(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiV2User', function() {
      it('should call getApiV2User successfully', function(done) {
        //uncomment below and update the code to test getApiV2User
        //instance.getApiV2User(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiV2UserByUserId', function() {
      it('should call getApiV2UserByUserId successfully', function(done) {
        //uncomment below and update the code to test getApiV2UserByUserId
        //instance.getApiV2UserByUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiV2UserSession', function() {
      it('should call getApiV2UserSession successfully', function(done) {
        //uncomment below and update the code to test getApiV2UserSession
        //instance.getApiV2UserSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchApiV2UserByUserId', function() {
      it('should call patchApiV2UserByUserId successfully', function(done) {
        //uncomment below and update the code to test patchApiV2UserByUserId
        //instance.patchApiV2UserByUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postApiV2Login', function() {
      it('should call postApiV2Login successfully', function(done) {
        //uncomment below and update the code to test postApiV2Login
        //instance.postApiV2Login(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postApiV2User', function() {
      it('should call postApiV2User successfully', function(done) {
        //uncomment below and update the code to test postApiV2User
        //instance.postApiV2User(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
