/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiClientEvaluationInfo from '../model/ApiClientEvaluationInfo';
import ApiClientTaskTemplateInfo from '../model/ApiClientTaskTemplateInfo';
import ErrorStatus from '../model/ErrorStatus';

/**
* EvaluationClient service.
* @module api/EvaluationClientApi
* @version 2.0.0-RC4
*/
export default class EvaluationClientApi {

    /**
    * Constructs a new EvaluationClientApi. 
    * @alias module:api/EvaluationClientApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getApiV2ClientEvaluationCurrentTaskByEvaluationId operation.
     * @callback module:api/EvaluationClientApi~getApiV2ClientEvaluationCurrentTaskByEvaluationIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ApiClientTaskTemplateInfo} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns an overview of the currently active task for a run.
     * @param {String} evaluationId The evaluation ID.
     * @param {Object} opts Optional parameters
     * @param {String} [session] Session Token
     * @param {module:api/EvaluationClientApi~getApiV2ClientEvaluationCurrentTaskByEvaluationIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ApiClientTaskTemplateInfo}
     */
    getApiV2ClientEvaluationCurrentTaskByEvaluationId(evaluationId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'evaluationId' is set
      if (evaluationId === undefined || evaluationId === null) {
        throw new Error("Missing the required parameter 'evaluationId' when calling getApiV2ClientEvaluationCurrentTaskByEvaluationId");
      }

      let pathParams = {
        'evaluationId': evaluationId
      };
      let queryParams = {
        'session': opts['session']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ApiClientTaskTemplateInfo;
      return this.apiClient.callApi(
        '/api/v2/client/evaluation/currentTask/{evaluationId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getApiV2ClientEvaluationList operation.
     * @callback module:api/EvaluationClientApi~getApiV2ClientEvaluationListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ApiClientEvaluationInfo>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lists an overview of all evaluation runs visible to the current client.
     * @param {Object} opts Optional parameters
     * @param {String} [session] Session Token
     * @param {module:api/EvaluationClientApi~getApiV2ClientEvaluationListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ApiClientEvaluationInfo>}
     */
    getApiV2ClientEvaluationList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'session': opts['session']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ApiClientEvaluationInfo];
      return this.apiClient.callApi(
        '/api/v2/client/evaluation/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
