/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CurrentTime from '../model/CurrentTime';

/**
* Status service.
* @module api/StatusApi
* @version 2.0.0-RC4
*/
export default class StatusApi {

    /**
    * Constructs a new StatusApi. 
    * @alias module:api/StatusApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getApiV2StatusTime operation.
     * @callback module:api/StatusApi~getApiV2StatusTimeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CurrentTime} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the current time on the server.
     * @param {module:api/StatusApi~getApiV2StatusTimeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CurrentTime}
     */
    getApiV2StatusTime(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CurrentTime;
      return this.apiClient.callApi(
        '/api/v2/status/time', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
