/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApiAnswer from './model/ApiAnswer';
import ApiAnswerSet from './model/ApiAnswerSet';
import ApiAnswerType from './model/ApiAnswerType';
import ApiClientAnswer from './model/ApiClientAnswer';
import ApiClientAnswerSet from './model/ApiClientAnswerSet';
import ApiClientEvaluationInfo from './model/ApiClientEvaluationInfo';
import ApiClientSubmission from './model/ApiClientSubmission';
import ApiClientTaskTemplateInfo from './model/ApiClientTaskTemplateInfo';
import ApiContentElement from './model/ApiContentElement';
import ApiContentType from './model/ApiContentType';
import ApiCreateEvaluation from './model/ApiCreateEvaluation';
import ApiEvaluation from './model/ApiEvaluation';
import ApiEvaluationInfo from './model/ApiEvaluationInfo';
import ApiEvaluationOverview from './model/ApiEvaluationOverview';
import ApiEvaluationStartMessage from './model/ApiEvaluationStartMessage';
import ApiEvaluationState from './model/ApiEvaluationState';
import ApiEvaluationStatus from './model/ApiEvaluationStatus';
import ApiEvaluationTemplate from './model/ApiEvaluationTemplate';
import ApiEvaluationTemplateOverview from './model/ApiEvaluationTemplateOverview';
import ApiEvaluationType from './model/ApiEvaluationType';
import ApiHint from './model/ApiHint';
import ApiHintContent from './model/ApiHintContent';
import ApiHintOption from './model/ApiHintOption';
import ApiHintType from './model/ApiHintType';
import ApiJudgement from './model/ApiJudgement';
import ApiJudgementRequest from './model/ApiJudgementRequest';
import ApiJudgementValidatorStatus from './model/ApiJudgementValidatorStatus';
import ApiMediaCollection from './model/ApiMediaCollection';
import ApiMediaItem from './model/ApiMediaItem';
import ApiMediaItemMetaDataEntry from './model/ApiMediaItemMetaDataEntry';
import ApiMediaType from './model/ApiMediaType';
import ApiOverrideAnswerSetVerdictDto from './model/ApiOverrideAnswerSetVerdictDto';
import ApiPopulatedMediaCollection from './model/ApiPopulatedMediaCollection';
import ApiRole from './model/ApiRole';
import ApiRunProperties from './model/ApiRunProperties';
import ApiScore from './model/ApiScore';
import ApiScoreOption from './model/ApiScoreOption';
import ApiScoreOverview from './model/ApiScoreOverview';
import ApiScoreSeries from './model/ApiScoreSeries';
import ApiScoreSeriesPoint from './model/ApiScoreSeriesPoint';
import ApiSubmission from './model/ApiSubmission';
import ApiSubmissionInfo from './model/ApiSubmissionInfo';
import ApiSubmissionOption from './model/ApiSubmissionOption';
import ApiTarget from './model/ApiTarget';
import ApiTargetContent from './model/ApiTargetContent';
import ApiTargetOption from './model/ApiTargetOption';
import ApiTargetType from './model/ApiTargetType';
import ApiTask from './model/ApiTask';
import ApiTaskGroup from './model/ApiTaskGroup';
import ApiTaskOption from './model/ApiTaskOption';
import ApiTaskOverview from './model/ApiTaskOverview';
import ApiTaskStatus from './model/ApiTaskStatus';
import ApiTaskTemplate from './model/ApiTaskTemplate';
import ApiTaskTemplateInfo from './model/ApiTaskTemplateInfo';
import ApiTaskType from './model/ApiTaskType';
import ApiTeam from './model/ApiTeam';
import ApiTeamAggregatorType from './model/ApiTeamAggregatorType';
import ApiTeamGroup from './model/ApiTeamGroup';
import ApiTeamGroupValue from './model/ApiTeamGroupValue';
import ApiTeamInfo from './model/ApiTeamInfo';
import ApiTeamTaskOverview from './model/ApiTeamTaskOverview';
import ApiTemporalPoint from './model/ApiTemporalPoint';
import ApiTemporalRange from './model/ApiTemporalRange';
import ApiTemporalUnit from './model/ApiTemporalUnit';
import ApiUser from './model/ApiUser';
import ApiUserRequest from './model/ApiUserRequest';
import ApiVerdictStatus from './model/ApiVerdictStatus';
import ApiViewerInfo from './model/ApiViewerInfo';
import ApiVote from './model/ApiVote';
import CurrentTime from './model/CurrentTime';
import DresInfo from './model/DresInfo';
import ErrorStatus from './model/ErrorStatus';
import LoginRequest from './model/LoginRequest';
import QueryEvent from './model/QueryEvent';
import QueryEventCategory from './model/QueryEventCategory';
import QueryEventLog from './model/QueryEventLog';
import QueryResultLog from './model/QueryResultLog';
import RankedAnswer from './model/RankedAnswer';
import RunManagerStatus from './model/RunManagerStatus';
import SuccessStatus from './model/SuccessStatus';
import SuccessfulSubmissionsStatus from './model/SuccessfulSubmissionsStatus';
import TemporalRange from './model/TemporalRange';
import EvaluationApi from './api/EvaluationApi';
import EvaluationClientApi from './api/EvaluationClientApi';
import LogApi from './api/LogApi';
import StatusApi from './api/StatusApi';
import SubmissionApi from './api/SubmissionApi';
import UserApi from './api/UserApi';


/**
* Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DresClientApi = require('index'); // See note below*.
* var xxxSvc = new DresClientApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DresClientApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DresClientApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DresClientApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0-RC4
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiAnswer model constructor.
     * @property {module:model/ApiAnswer}
     */
    ApiAnswer,

    /**
     * The ApiAnswerSet model constructor.
     * @property {module:model/ApiAnswerSet}
     */
    ApiAnswerSet,

    /**
     * The ApiAnswerType model constructor.
     * @property {module:model/ApiAnswerType}
     */
    ApiAnswerType,

    /**
     * The ApiClientAnswer model constructor.
     * @property {module:model/ApiClientAnswer}
     */
    ApiClientAnswer,

    /**
     * The ApiClientAnswerSet model constructor.
     * @property {module:model/ApiClientAnswerSet}
     */
    ApiClientAnswerSet,

    /**
     * The ApiClientEvaluationInfo model constructor.
     * @property {module:model/ApiClientEvaluationInfo}
     */
    ApiClientEvaluationInfo,

    /**
     * The ApiClientSubmission model constructor.
     * @property {module:model/ApiClientSubmission}
     */
    ApiClientSubmission,

    /**
     * The ApiClientTaskTemplateInfo model constructor.
     * @property {module:model/ApiClientTaskTemplateInfo}
     */
    ApiClientTaskTemplateInfo,

    /**
     * The ApiContentElement model constructor.
     * @property {module:model/ApiContentElement}
     */
    ApiContentElement,

    /**
     * The ApiContentType model constructor.
     * @property {module:model/ApiContentType}
     */
    ApiContentType,

    /**
     * The ApiCreateEvaluation model constructor.
     * @property {module:model/ApiCreateEvaluation}
     */
    ApiCreateEvaluation,

    /**
     * The ApiEvaluation model constructor.
     * @property {module:model/ApiEvaluation}
     */
    ApiEvaluation,

    /**
     * The ApiEvaluationInfo model constructor.
     * @property {module:model/ApiEvaluationInfo}
     */
    ApiEvaluationInfo,

    /**
     * The ApiEvaluationOverview model constructor.
     * @property {module:model/ApiEvaluationOverview}
     */
    ApiEvaluationOverview,

    /**
     * The ApiEvaluationStartMessage model constructor.
     * @property {module:model/ApiEvaluationStartMessage}
     */
    ApiEvaluationStartMessage,

    /**
     * The ApiEvaluationState model constructor.
     * @property {module:model/ApiEvaluationState}
     */
    ApiEvaluationState,

    /**
     * The ApiEvaluationStatus model constructor.
     * @property {module:model/ApiEvaluationStatus}
     */
    ApiEvaluationStatus,

    /**
     * The ApiEvaluationTemplate model constructor.
     * @property {module:model/ApiEvaluationTemplate}
     */
    ApiEvaluationTemplate,

    /**
     * The ApiEvaluationTemplateOverview model constructor.
     * @property {module:model/ApiEvaluationTemplateOverview}
     */
    ApiEvaluationTemplateOverview,

    /**
     * The ApiEvaluationType model constructor.
     * @property {module:model/ApiEvaluationType}
     */
    ApiEvaluationType,

    /**
     * The ApiHint model constructor.
     * @property {module:model/ApiHint}
     */
    ApiHint,

    /**
     * The ApiHintContent model constructor.
     * @property {module:model/ApiHintContent}
     */
    ApiHintContent,

    /**
     * The ApiHintOption model constructor.
     * @property {module:model/ApiHintOption}
     */
    ApiHintOption,

    /**
     * The ApiHintType model constructor.
     * @property {module:model/ApiHintType}
     */
    ApiHintType,

    /**
     * The ApiJudgement model constructor.
     * @property {module:model/ApiJudgement}
     */
    ApiJudgement,

    /**
     * The ApiJudgementRequest model constructor.
     * @property {module:model/ApiJudgementRequest}
     */
    ApiJudgementRequest,

    /**
     * The ApiJudgementValidatorStatus model constructor.
     * @property {module:model/ApiJudgementValidatorStatus}
     */
    ApiJudgementValidatorStatus,

    /**
     * The ApiMediaCollection model constructor.
     * @property {module:model/ApiMediaCollection}
     */
    ApiMediaCollection,

    /**
     * The ApiMediaItem model constructor.
     * @property {module:model/ApiMediaItem}
     */
    ApiMediaItem,

    /**
     * The ApiMediaItemMetaDataEntry model constructor.
     * @property {module:model/ApiMediaItemMetaDataEntry}
     */
    ApiMediaItemMetaDataEntry,

    /**
     * The ApiMediaType model constructor.
     * @property {module:model/ApiMediaType}
     */
    ApiMediaType,

    /**
     * The ApiOverrideAnswerSetVerdictDto model constructor.
     * @property {module:model/ApiOverrideAnswerSetVerdictDto}
     */
    ApiOverrideAnswerSetVerdictDto,

    /**
     * The ApiPopulatedMediaCollection model constructor.
     * @property {module:model/ApiPopulatedMediaCollection}
     */
    ApiPopulatedMediaCollection,

    /**
     * The ApiRole model constructor.
     * @property {module:model/ApiRole}
     */
    ApiRole,

    /**
     * The ApiRunProperties model constructor.
     * @property {module:model/ApiRunProperties}
     */
    ApiRunProperties,

    /**
     * The ApiScore model constructor.
     * @property {module:model/ApiScore}
     */
    ApiScore,

    /**
     * The ApiScoreOption model constructor.
     * @property {module:model/ApiScoreOption}
     */
    ApiScoreOption,

    /**
     * The ApiScoreOverview model constructor.
     * @property {module:model/ApiScoreOverview}
     */
    ApiScoreOverview,

    /**
     * The ApiScoreSeries model constructor.
     * @property {module:model/ApiScoreSeries}
     */
    ApiScoreSeries,

    /**
     * The ApiScoreSeriesPoint model constructor.
     * @property {module:model/ApiScoreSeriesPoint}
     */
    ApiScoreSeriesPoint,

    /**
     * The ApiSubmission model constructor.
     * @property {module:model/ApiSubmission}
     */
    ApiSubmission,

    /**
     * The ApiSubmissionInfo model constructor.
     * @property {module:model/ApiSubmissionInfo}
     */
    ApiSubmissionInfo,

    /**
     * The ApiSubmissionOption model constructor.
     * @property {module:model/ApiSubmissionOption}
     */
    ApiSubmissionOption,

    /**
     * The ApiTarget model constructor.
     * @property {module:model/ApiTarget}
     */
    ApiTarget,

    /**
     * The ApiTargetContent model constructor.
     * @property {module:model/ApiTargetContent}
     */
    ApiTargetContent,

    /**
     * The ApiTargetOption model constructor.
     * @property {module:model/ApiTargetOption}
     */
    ApiTargetOption,

    /**
     * The ApiTargetType model constructor.
     * @property {module:model/ApiTargetType}
     */
    ApiTargetType,

    /**
     * The ApiTask model constructor.
     * @property {module:model/ApiTask}
     */
    ApiTask,

    /**
     * The ApiTaskGroup model constructor.
     * @property {module:model/ApiTaskGroup}
     */
    ApiTaskGroup,

    /**
     * The ApiTaskOption model constructor.
     * @property {module:model/ApiTaskOption}
     */
    ApiTaskOption,

    /**
     * The ApiTaskOverview model constructor.
     * @property {module:model/ApiTaskOverview}
     */
    ApiTaskOverview,

    /**
     * The ApiTaskStatus model constructor.
     * @property {module:model/ApiTaskStatus}
     */
    ApiTaskStatus,

    /**
     * The ApiTaskTemplate model constructor.
     * @property {module:model/ApiTaskTemplate}
     */
    ApiTaskTemplate,

    /**
     * The ApiTaskTemplateInfo model constructor.
     * @property {module:model/ApiTaskTemplateInfo}
     */
    ApiTaskTemplateInfo,

    /**
     * The ApiTaskType model constructor.
     * @property {module:model/ApiTaskType}
     */
    ApiTaskType,

    /**
     * The ApiTeam model constructor.
     * @property {module:model/ApiTeam}
     */
    ApiTeam,

    /**
     * The ApiTeamAggregatorType model constructor.
     * @property {module:model/ApiTeamAggregatorType}
     */
    ApiTeamAggregatorType,

    /**
     * The ApiTeamGroup model constructor.
     * @property {module:model/ApiTeamGroup}
     */
    ApiTeamGroup,

    /**
     * The ApiTeamGroupValue model constructor.
     * @property {module:model/ApiTeamGroupValue}
     */
    ApiTeamGroupValue,

    /**
     * The ApiTeamInfo model constructor.
     * @property {module:model/ApiTeamInfo}
     */
    ApiTeamInfo,

    /**
     * The ApiTeamTaskOverview model constructor.
     * @property {module:model/ApiTeamTaskOverview}
     */
    ApiTeamTaskOverview,

    /**
     * The ApiTemporalPoint model constructor.
     * @property {module:model/ApiTemporalPoint}
     */
    ApiTemporalPoint,

    /**
     * The ApiTemporalRange model constructor.
     * @property {module:model/ApiTemporalRange}
     */
    ApiTemporalRange,

    /**
     * The ApiTemporalUnit model constructor.
     * @property {module:model/ApiTemporalUnit}
     */
    ApiTemporalUnit,

    /**
     * The ApiUser model constructor.
     * @property {module:model/ApiUser}
     */
    ApiUser,

    /**
     * The ApiUserRequest model constructor.
     * @property {module:model/ApiUserRequest}
     */
    ApiUserRequest,

    /**
     * The ApiVerdictStatus model constructor.
     * @property {module:model/ApiVerdictStatus}
     */
    ApiVerdictStatus,

    /**
     * The ApiViewerInfo model constructor.
     * @property {module:model/ApiViewerInfo}
     */
    ApiViewerInfo,

    /**
     * The ApiVote model constructor.
     * @property {module:model/ApiVote}
     */
    ApiVote,

    /**
     * The CurrentTime model constructor.
     * @property {module:model/CurrentTime}
     */
    CurrentTime,

    /**
     * The DresInfo model constructor.
     * @property {module:model/DresInfo}
     */
    DresInfo,

    /**
     * The ErrorStatus model constructor.
     * @property {module:model/ErrorStatus}
     */
    ErrorStatus,

    /**
     * The LoginRequest model constructor.
     * @property {module:model/LoginRequest}
     */
    LoginRequest,

    /**
     * The QueryEvent model constructor.
     * @property {module:model/QueryEvent}
     */
    QueryEvent,

    /**
     * The QueryEventCategory model constructor.
     * @property {module:model/QueryEventCategory}
     */
    QueryEventCategory,

    /**
     * The QueryEventLog model constructor.
     * @property {module:model/QueryEventLog}
     */
    QueryEventLog,

    /**
     * The QueryResultLog model constructor.
     * @property {module:model/QueryResultLog}
     */
    QueryResultLog,

    /**
     * The RankedAnswer model constructor.
     * @property {module:model/RankedAnswer}
     */
    RankedAnswer,

    /**
     * The RunManagerStatus model constructor.
     * @property {module:model/RunManagerStatus}
     */
    RunManagerStatus,

    /**
     * The SuccessStatus model constructor.
     * @property {module:model/SuccessStatus}
     */
    SuccessStatus,

    /**
     * The SuccessfulSubmissionsStatus model constructor.
     * @property {module:model/SuccessfulSubmissionsStatus}
     */
    SuccessfulSubmissionsStatus,

    /**
     * The TemporalRange model constructor.
     * @property {module:model/TemporalRange}
     */
    TemporalRange,

    /**
    * The EvaluationApi service constructor.
    * @property {module:api/EvaluationApi}
    */
    EvaluationApi,

    /**
    * The EvaluationClientApi service constructor.
    * @property {module:api/EvaluationClientApi}
    */
    EvaluationClientApi,

    /**
    * The LogApi service constructor.
    * @property {module:api/LogApi}
    */
    LogApi,

    /**
    * The StatusApi service constructor.
    * @property {module:api/StatusApi}
    */
    StatusApi,

    /**
    * The SubmissionApi service constructor.
    * @property {module:api/SubmissionApi}
    */
    SubmissionApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
