/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiAnswerType from './ApiAnswerType';
import ApiMediaItem from './ApiMediaItem';
import TemporalRange from './TemporalRange';

/**
 * The ApiAnswer model module.
 * @module model/ApiAnswer
 * @version 2.0.0-RC4
 */
class ApiAnswer {
    /**
     * Constructs a new <code>ApiAnswer</code>.
     * @alias module:model/ApiAnswer
     * @param type {module:model/ApiAnswerType} 
     */
    constructor(type) { 
        
        ApiAnswer.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>ApiAnswer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiAnswer} obj Optional instance to populate.
     * @return {module:model/ApiAnswer} The populated <code>ApiAnswer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiAnswer();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiAnswerType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = ApiMediaItem.constructFromObject(data['item']);
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Number');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'Number');
            }
            if (data.hasOwnProperty('temporalRange')) {
                obj['temporalRange'] = TemporalRange.constructFromObject(data['temporalRange']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiAnswer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiAnswer</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiAnswer.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `item`
        if (data['item']) { // data not null
          ApiMediaItem.validateJSON(data['item']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // validate the optional field `temporalRange`
        if (data['temporalRange']) { // data not null
          TemporalRange.validateJSON(data['temporalRange']);
        }

        return true;
    }


}

ApiAnswer.RequiredProperties = ["type"];

/**
 * @member {module:model/ApiAnswerType} type
 */
ApiAnswer.prototype['type'] = undefined;

/**
 * @member {module:model/ApiMediaItem} item
 */
ApiAnswer.prototype['item'] = undefined;

/**
 * @member {String} text
 */
ApiAnswer.prototype['text'] = undefined;

/**
 * @member {Number} start
 */
ApiAnswer.prototype['start'] = undefined;

/**
 * @member {Number} end
 */
ApiAnswer.prototype['end'] = undefined;

/**
 * @member {module:model/TemporalRange} temporalRange
 */
ApiAnswer.prototype['temporalRange'] = undefined;






export default ApiAnswer;

