/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiClientTaskTemplateInfo from './ApiClientTaskTemplateInfo';
import ApiEvaluationStatus from './ApiEvaluationStatus';
import ApiEvaluationType from './ApiEvaluationType';

/**
 * The ApiClientEvaluationInfo model module.
 * @module model/ApiClientEvaluationInfo
 * @version 2.0.0-RC4
 */
class ApiClientEvaluationInfo {
    /**
     * Constructs a new <code>ApiClientEvaluationInfo</code>.
     * @alias module:model/ApiClientEvaluationInfo
     * @param id {String} 
     * @param name {String} 
     * @param type {module:model/ApiEvaluationType} 
     * @param status {module:model/ApiEvaluationStatus} 
     * @param templateId {String} 
     * @param teams {Array.<String>} 
     * @param taskTemplates {Array.<module:model/ApiClientTaskTemplateInfo>} 
     */
    constructor(id, name, type, status, templateId, teams, taskTemplates) { 
        
        ApiClientEvaluationInfo.initialize(this, id, name, type, status, templateId, teams, taskTemplates);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, type, status, templateId, teams, taskTemplates) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['type'] = type;
        obj['status'] = status;
        obj['templateId'] = templateId;
        obj['teams'] = teams;
        obj['taskTemplates'] = taskTemplates;
    }

    /**
     * Constructs a <code>ApiClientEvaluationInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiClientEvaluationInfo} obj Optional instance to populate.
     * @return {module:model/ApiClientEvaluationInfo} The populated <code>ApiClientEvaluationInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiClientEvaluationInfo();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiEvaluationType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiEvaluationStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'String');
            }
            if (data.hasOwnProperty('templateDescription')) {
                obj['templateDescription'] = ApiClient.convertToType(data['templateDescription'], 'String');
            }
            if (data.hasOwnProperty('teams')) {
                obj['teams'] = ApiClient.convertToType(data['teams'], ['String']);
            }
            if (data.hasOwnProperty('taskTemplates')) {
                obj['taskTemplates'] = ApiClient.convertToType(data['taskTemplates'], [ApiClientTaskTemplateInfo]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiClientEvaluationInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiClientEvaluationInfo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiClientEvaluationInfo.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['templateId'] && !(typeof data['templateId'] === 'string' || data['templateId'] instanceof String)) {
            throw new Error("Expected the field `templateId` to be a primitive type in the JSON string but got " + data['templateId']);
        }
        // ensure the json data is a string
        if (data['templateDescription'] && !(typeof data['templateDescription'] === 'string' || data['templateDescription'] instanceof String)) {
            throw new Error("Expected the field `templateDescription` to be a primitive type in the JSON string but got " + data['templateDescription']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['teams'])) {
            throw new Error("Expected the field `teams` to be an array in the JSON data but got " + data['teams']);
        }
        if (data['taskTemplates']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['taskTemplates'])) {
                throw new Error("Expected the field `taskTemplates` to be an array in the JSON data but got " + data['taskTemplates']);
            }
            // validate the optional field `taskTemplates` (array)
            for (const item of data['taskTemplates']) {
                ApiClientTaskTemplateInfo.validateJSON(item);
            };
        }

        return true;
    }


}

ApiClientEvaluationInfo.RequiredProperties = ["id", "name", "type", "status", "templateId", "teams", "taskTemplates"];

/**
 * @member {String} id
 */
ApiClientEvaluationInfo.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ApiClientEvaluationInfo.prototype['name'] = undefined;

/**
 * @member {module:model/ApiEvaluationType} type
 */
ApiClientEvaluationInfo.prototype['type'] = undefined;

/**
 * @member {module:model/ApiEvaluationStatus} status
 */
ApiClientEvaluationInfo.prototype['status'] = undefined;

/**
 * @member {String} templateId
 */
ApiClientEvaluationInfo.prototype['templateId'] = undefined;

/**
 * @member {String} templateDescription
 */
ApiClientEvaluationInfo.prototype['templateDescription'] = undefined;

/**
 * @member {Array.<String>} teams
 */
ApiClientEvaluationInfo.prototype['teams'] = undefined;

/**
 * @member {Array.<module:model/ApiClientTaskTemplateInfo>} taskTemplates
 */
ApiClientEvaluationInfo.prototype['taskTemplates'] = undefined;






export default ApiClientEvaluationInfo;

