/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiClientAnswer model module.
 * @module model/ApiClientAnswer
 * @version 2.0.0-RC4
 */
class ApiClientAnswer {
    /**
     * Constructs a new <code>ApiClientAnswer</code>.
     * @alias module:model/ApiClientAnswer
     */
    constructor() { 
        
        ApiClientAnswer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiClientAnswer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiClientAnswer} obj Optional instance to populate.
     * @return {module:model/ApiClientAnswer} The populated <code>ApiClientAnswer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiClientAnswer();

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('mediaItemName')) {
                obj['mediaItemName'] = ApiClient.convertToType(data['mediaItemName'], 'String');
            }
            if (data.hasOwnProperty('mediaItemCollectionName')) {
                obj['mediaItemCollectionName'] = ApiClient.convertToType(data['mediaItemCollectionName'], 'String');
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Number');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiClientAnswer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiClientAnswer</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // ensure the json data is a string
        if (data['mediaItemName'] && !(typeof data['mediaItemName'] === 'string' || data['mediaItemName'] instanceof String)) {
            throw new Error("Expected the field `mediaItemName` to be a primitive type in the JSON string but got " + data['mediaItemName']);
        }
        // ensure the json data is a string
        if (data['mediaItemCollectionName'] && !(typeof data['mediaItemCollectionName'] === 'string' || data['mediaItemCollectionName'] instanceof String)) {
            throw new Error("Expected the field `mediaItemCollectionName` to be a primitive type in the JSON string but got " + data['mediaItemCollectionName']);
        }

        return true;
    }


}



/**
 * @member {String} text
 */
ApiClientAnswer.prototype['text'] = undefined;

/**
 * @member {String} mediaItemName
 */
ApiClientAnswer.prototype['mediaItemName'] = undefined;

/**
 * @member {String} mediaItemCollectionName
 */
ApiClientAnswer.prototype['mediaItemCollectionName'] = undefined;

/**
 * @member {Number} start
 */
ApiClientAnswer.prototype['start'] = undefined;

/**
 * @member {Number} end
 */
ApiClientAnswer.prototype['end'] = undefined;






export default ApiClientAnswer;

