/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApiContentType.
* @enum {}
* @readonly
*/
export default class ApiContentType {
    
        /**
         * value: "EMPTY"
         * @const
         */
        "EMPTY" = "EMPTY";

    
        /**
         * value: "TEXT"
         * @const
         */
        "TEXT" = "TEXT";

    
        /**
         * value: "VIDEO"
         * @const
         */
        "VIDEO" = "VIDEO";

    
        /**
         * value: "IMAGE"
         * @const
         */
        "IMAGE" = "IMAGE";

    

    /**
    * Returns a <code>ApiContentType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApiContentType} The enum <code>ApiContentType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

