/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiClientAnswer from './ApiClientAnswer';

/**
 * The ApiClientAnswerSet model module.
 * @module model/ApiClientAnswerSet
 * @version 2.0.0-RC4
 */
class ApiClientAnswerSet {
    /**
     * Constructs a new <code>ApiClientAnswerSet</code>.
     * @alias module:model/ApiClientAnswerSet
     * @param answers {Array.<module:model/ApiClientAnswer>} 
     */
    constructor(answers) { 
        
        ApiClientAnswerSet.initialize(this, answers);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, answers) { 
        obj['answers'] = answers;
    }

    /**
     * Constructs a <code>ApiClientAnswerSet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiClientAnswerSet} obj Optional instance to populate.
     * @return {module:model/ApiClientAnswerSet} The populated <code>ApiClientAnswerSet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiClientAnswerSet();

            if (data.hasOwnProperty('taskId')) {
                obj['taskId'] = ApiClient.convertToType(data['taskId'], 'String');
            }
            if (data.hasOwnProperty('taskName')) {
                obj['taskName'] = ApiClient.convertToType(data['taskName'], 'String');
            }
            if (data.hasOwnProperty('answers')) {
                obj['answers'] = ApiClient.convertToType(data['answers'], [ApiClientAnswer]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiClientAnswerSet</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiClientAnswerSet</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiClientAnswerSet.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['taskId'] && !(typeof data['taskId'] === 'string' || data['taskId'] instanceof String)) {
            throw new Error("Expected the field `taskId` to be a primitive type in the JSON string but got " + data['taskId']);
        }
        // ensure the json data is a string
        if (data['taskName'] && !(typeof data['taskName'] === 'string' || data['taskName'] instanceof String)) {
            throw new Error("Expected the field `taskName` to be a primitive type in the JSON string but got " + data['taskName']);
        }
        if (data['answers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['answers'])) {
                throw new Error("Expected the field `answers` to be an array in the JSON data but got " + data['answers']);
            }
            // validate the optional field `answers` (array)
            for (const item of data['answers']) {
                ApiClientAnswer.validateJSON(item);
            };
        }

        return true;
    }


}

ApiClientAnswerSet.RequiredProperties = ["answers"];

/**
 * @member {String} taskId
 */
ApiClientAnswerSet.prototype['taskId'] = undefined;

/**
 * @member {String} taskName
 */
ApiClientAnswerSet.prototype['taskName'] = undefined;

/**
 * @member {Array.<module:model/ApiClientAnswer>} answers
 */
ApiClientAnswerSet.prototype['answers'] = undefined;






export default ApiClientAnswerSet;

