/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiEvaluationTemplateOverview model module.
 * @module model/ApiEvaluationTemplateOverview
 * @version 2.0.0-RC4
 */
class ApiEvaluationTemplateOverview {
    /**
     * Constructs a new <code>ApiEvaluationTemplateOverview</code>.
     * @alias module:model/ApiEvaluationTemplateOverview
     * @param id {String} 
     * @param name {String} 
     * @param taskCount {Number} 
     * @param teamCount {Number} 
     */
    constructor(id, name, taskCount, teamCount) { 
        
        ApiEvaluationTemplateOverview.initialize(this, id, name, taskCount, teamCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, taskCount, teamCount) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['taskCount'] = taskCount;
        obj['teamCount'] = teamCount;
    }

    /**
     * Constructs a <code>ApiEvaluationTemplateOverview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiEvaluationTemplateOverview} obj Optional instance to populate.
     * @return {module:model/ApiEvaluationTemplateOverview} The populated <code>ApiEvaluationTemplateOverview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiEvaluationTemplateOverview();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('taskCount')) {
                obj['taskCount'] = ApiClient.convertToType(data['taskCount'], 'Number');
            }
            if (data.hasOwnProperty('teamCount')) {
                obj['teamCount'] = ApiClient.convertToType(data['teamCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiEvaluationTemplateOverview</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiEvaluationTemplateOverview</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiEvaluationTemplateOverview.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

ApiEvaluationTemplateOverview.RequiredProperties = ["id", "name", "taskCount", "teamCount"];

/**
 * @member {String} id
 */
ApiEvaluationTemplateOverview.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ApiEvaluationTemplateOverview.prototype['name'] = undefined;

/**
 * @member {String} description
 */
ApiEvaluationTemplateOverview.prototype['description'] = undefined;

/**
 * @member {Number} taskCount
 */
ApiEvaluationTemplateOverview.prototype['taskCount'] = undefined;

/**
 * @member {Number} teamCount
 */
ApiEvaluationTemplateOverview.prototype['teamCount'] = undefined;






export default ApiEvaluationTemplateOverview;

