/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiTeamTaskOverview from './ApiTeamTaskOverview';
import RunManagerStatus from './RunManagerStatus';

/**
 * The ApiEvaluationOverview model module.
 * @module model/ApiEvaluationOverview
 * @version 2.0.0-RC4
 */
class ApiEvaluationOverview {
    /**
     * Constructs a new <code>ApiEvaluationOverview</code>.
     * @alias module:model/ApiEvaluationOverview
     * @param state {module:model/RunManagerStatus} 
     * @param teamOverviews {Array.<module:model/ApiTeamTaskOverview>} 
     */
    constructor(state, teamOverviews) { 
        
        ApiEvaluationOverview.initialize(this, state, teamOverviews);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, state, teamOverviews) { 
        obj['state'] = state;
        obj['teamOverviews'] = teamOverviews;
    }

    /**
     * Constructs a <code>ApiEvaluationOverview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiEvaluationOverview} obj Optional instance to populate.
     * @return {module:model/ApiEvaluationOverview} The populated <code>ApiEvaluationOverview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiEvaluationOverview();

            if (data.hasOwnProperty('state')) {
                obj['state'] = RunManagerStatus.constructFromObject(data['state']);
            }
            if (data.hasOwnProperty('teamOverviews')) {
                obj['teamOverviews'] = ApiClient.convertToType(data['teamOverviews'], [ApiTeamTaskOverview]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiEvaluationOverview</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiEvaluationOverview</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiEvaluationOverview.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['teamOverviews']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['teamOverviews'])) {
                throw new Error("Expected the field `teamOverviews` to be an array in the JSON data but got " + data['teamOverviews']);
            }
            // validate the optional field `teamOverviews` (array)
            for (const item of data['teamOverviews']) {
                ApiTeamTaskOverview.validateJSON(item);
            };
        }

        return true;
    }


}

ApiEvaluationOverview.RequiredProperties = ["state", "teamOverviews"];

/**
 * @member {module:model/RunManagerStatus} state
 */
ApiEvaluationOverview.prototype['state'] = undefined;

/**
 * @member {Array.<module:model/ApiTeamTaskOverview>} teamOverviews
 */
ApiEvaluationOverview.prototype['teamOverviews'] = undefined;






export default ApiEvaluationOverview;

