/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApiEvaluationStatus.
* @enum {}
* @readonly
*/
export default class ApiEvaluationStatus {
    
        /**
         * value: "CREATED"
         * @const
         */
        "CREATED" = "CREATED";

    
        /**
         * value: "ACTIVE"
         * @const
         */
        "ACTIVE" = "ACTIVE";

    
        /**
         * value: "TERMINATED"
         * @const
         */
        "TERMINATED" = "TERMINATED";

    

    /**
    * Returns a <code>ApiEvaluationStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApiEvaluationStatus} The enum <code>ApiEvaluationStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

