/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiEvaluationType from './ApiEvaluationType';
import ApiRunProperties from './ApiRunProperties';

/**
 * The ApiEvaluationStartMessage model module.
 * @module model/ApiEvaluationStartMessage
 * @version 2.0.0-RC4
 */
class ApiEvaluationStartMessage {
    /**
     * Constructs a new <code>ApiEvaluationStartMessage</code>.
     * @alias module:model/ApiEvaluationStartMessage
     * @param templateId {String} 
     * @param name {String} 
     * @param type {module:model/ApiEvaluationType} 
     * @param properties {module:model/ApiRunProperties} 
     */
    constructor(templateId, name, type, properties) { 
        
        ApiEvaluationStartMessage.initialize(this, templateId, name, type, properties);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, templateId, name, type, properties) { 
        obj['templateId'] = templateId;
        obj['name'] = name;
        obj['type'] = type;
        obj['properties'] = properties;
    }

    /**
     * Constructs a <code>ApiEvaluationStartMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiEvaluationStartMessage} obj Optional instance to populate.
     * @return {module:model/ApiEvaluationStartMessage} The populated <code>ApiEvaluationStartMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiEvaluationStartMessage();

            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiEvaluationType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiRunProperties.constructFromObject(data['properties']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiEvaluationStartMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiEvaluationStartMessage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiEvaluationStartMessage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['templateId'] && !(typeof data['templateId'] === 'string' || data['templateId'] instanceof String)) {
            throw new Error("Expected the field `templateId` to be a primitive type in the JSON string but got " + data['templateId']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `properties`
        if (data['properties']) { // data not null
          ApiRunProperties.validateJSON(data['properties']);
        }

        return true;
    }


}

ApiEvaluationStartMessage.RequiredProperties = ["templateId", "name", "type", "properties"];

/**
 * @member {String} templateId
 */
ApiEvaluationStartMessage.prototype['templateId'] = undefined;

/**
 * @member {String} name
 */
ApiEvaluationStartMessage.prototype['name'] = undefined;

/**
 * @member {module:model/ApiEvaluationType} type
 */
ApiEvaluationStartMessage.prototype['type'] = undefined;

/**
 * @member {module:model/ApiRunProperties} properties
 */
ApiEvaluationStartMessage.prototype['properties'] = undefined;






export default ApiEvaluationStartMessage;

