/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApiEvaluationType.
* @enum {}
* @readonly
*/
export default class ApiEvaluationType {
    
        /**
         * value: "SYNCHRONOUS"
         * @const
         */
        "SYNCHRONOUS" = "SYNCHRONOUS";

    
        /**
         * value: "ASYNCHRONOUS"
         * @const
         */
        "ASYNCHRONOUS" = "ASYNCHRONOUS";

    
        /**
         * value: "NON_INTERACTIVE"
         * @const
         */
        "NON_INTERACTIVE" = "NON_INTERACTIVE";

    

    /**
    * Returns a <code>ApiEvaluationType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApiEvaluationType} The enum <code>ApiEvaluationType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

