/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApiHintOption.
* @enum {}
* @readonly
*/
export default class ApiHintOption {
    
        /**
         * value: "IMAGE_ITEM"
         * @const
         */
        "IMAGE_ITEM" = "IMAGE_ITEM";

    
        /**
         * value: "VIDEO_ITEM_SEGMENT"
         * @const
         */
        "VIDEO_ITEM_SEGMENT" = "VIDEO_ITEM_SEGMENT";

    
        /**
         * value: "TEXT"
         * @const
         */
        "TEXT" = "TEXT";

    
        /**
         * value: "EXTERNAL_IMAGE"
         * @const
         */
        "EXTERNAL_IMAGE" = "EXTERNAL_IMAGE";

    
        /**
         * value: "EXTERNAL_VIDEO"
         * @const
         */
        "EXTERNAL_VIDEO" = "EXTERNAL_VIDEO";

    

    /**
    * Returns a <code>ApiHintOption</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApiHintOption} The enum <code>ApiHintOption</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

