/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiJudgementValidatorStatus model module.
 * @module model/ApiJudgementValidatorStatus
 * @version 2.0.0-RC4
 */
class ApiJudgementValidatorStatus {
    /**
     * Constructs a new <code>ApiJudgementValidatorStatus</code>.
     * @alias module:model/ApiJudgementValidatorStatus
     * @param validatorName {String} 
     * @param pending {Number} 
     * @param open {Number} 
     */
    constructor(validatorName, pending, open) { 
        
        ApiJudgementValidatorStatus.initialize(this, validatorName, pending, open);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, validatorName, pending, open) { 
        obj['validatorName'] = validatorName;
        obj['pending'] = pending;
        obj['open'] = open;
    }

    /**
     * Constructs a <code>ApiJudgementValidatorStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiJudgementValidatorStatus} obj Optional instance to populate.
     * @return {module:model/ApiJudgementValidatorStatus} The populated <code>ApiJudgementValidatorStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiJudgementValidatorStatus();

            if (data.hasOwnProperty('validatorName')) {
                obj['validatorName'] = ApiClient.convertToType(data['validatorName'], 'String');
            }
            if (data.hasOwnProperty('pending')) {
                obj['pending'] = ApiClient.convertToType(data['pending'], 'Number');
            }
            if (data.hasOwnProperty('open')) {
                obj['open'] = ApiClient.convertToType(data['open'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiJudgementValidatorStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiJudgementValidatorStatus</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiJudgementValidatorStatus.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['validatorName'] && !(typeof data['validatorName'] === 'string' || data['validatorName'] instanceof String)) {
            throw new Error("Expected the field `validatorName` to be a primitive type in the JSON string but got " + data['validatorName']);
        }

        return true;
    }


}

ApiJudgementValidatorStatus.RequiredProperties = ["validatorName", "pending", "open"];

/**
 * @member {String} validatorName
 */
ApiJudgementValidatorStatus.prototype['validatorName'] = undefined;

/**
 * @member {Number} pending
 */
ApiJudgementValidatorStatus.prototype['pending'] = undefined;

/**
 * @member {Number} open
 */
ApiJudgementValidatorStatus.prototype['open'] = undefined;






export default ApiJudgementValidatorStatus;

