/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiAnswerSet from './ApiAnswerSet';

/**
 * The ApiJudgementRequest model module.
 * @module model/ApiJudgementRequest
 * @version 2.0.0-RC4
 */
class ApiJudgementRequest {
    /**
     * Constructs a new <code>ApiJudgementRequest</code>.
     * @alias module:model/ApiJudgementRequest
     * @param validator {String} 
     * @param taskDescription {String} 
     * @param answerSet {module:model/ApiAnswerSet} 
     */
    constructor(validator, taskDescription, answerSet) { 
        
        ApiJudgementRequest.initialize(this, validator, taskDescription, answerSet);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, validator, taskDescription, answerSet) { 
        obj['validator'] = validator;
        obj['taskDescription'] = taskDescription;
        obj['answerSet'] = answerSet;
    }

    /**
     * Constructs a <code>ApiJudgementRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiJudgementRequest} obj Optional instance to populate.
     * @return {module:model/ApiJudgementRequest} The populated <code>ApiJudgementRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiJudgementRequest();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('validator')) {
                obj['validator'] = ApiClient.convertToType(data['validator'], 'String');
            }
            if (data.hasOwnProperty('taskDescription')) {
                obj['taskDescription'] = ApiClient.convertToType(data['taskDescription'], 'String');
            }
            if (data.hasOwnProperty('answerSet')) {
                obj['answerSet'] = ApiAnswerSet.constructFromObject(data['answerSet']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiJudgementRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiJudgementRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiJudgementRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['validator'] && !(typeof data['validator'] === 'string' || data['validator'] instanceof String)) {
            throw new Error("Expected the field `validator` to be a primitive type in the JSON string but got " + data['validator']);
        }
        // ensure the json data is a string
        if (data['taskDescription'] && !(typeof data['taskDescription'] === 'string' || data['taskDescription'] instanceof String)) {
            throw new Error("Expected the field `taskDescription` to be a primitive type in the JSON string but got " + data['taskDescription']);
        }
        // validate the optional field `answerSet`
        if (data['answerSet']) { // data not null
          ApiAnswerSet.validateJSON(data['answerSet']);
        }

        return true;
    }


}

ApiJudgementRequest.RequiredProperties = ["validator", "taskDescription", "answerSet"];

/**
 * @member {String} token
 */
ApiJudgementRequest.prototype['token'] = undefined;

/**
 * @member {String} validator
 */
ApiJudgementRequest.prototype['validator'] = undefined;

/**
 * @member {String} taskDescription
 */
ApiJudgementRequest.prototype['taskDescription'] = undefined;

/**
 * @member {module:model/ApiAnswerSet} answerSet
 */
ApiJudgementRequest.prototype['answerSet'] = undefined;






export default ApiJudgementRequest;

