/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiVerdictStatus from './ApiVerdictStatus';

/**
 * The ApiJudgement model module.
 * @module model/ApiJudgement
 * @version 2.0.0-RC4
 */
class ApiJudgement {
    /**
     * Constructs a new <code>ApiJudgement</code>.
     * @alias module:model/ApiJudgement
     * @param token {String} 
     * @param validator {String} 
     * @param verdict {module:model/ApiVerdictStatus} 
     */
    constructor(token, validator, verdict) { 
        
        ApiJudgement.initialize(this, token, validator, verdict);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token, validator, verdict) { 
        obj['token'] = token;
        obj['validator'] = validator;
        obj['verdict'] = verdict;
    }

    /**
     * Constructs a <code>ApiJudgement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiJudgement} obj Optional instance to populate.
     * @return {module:model/ApiJudgement} The populated <code>ApiJudgement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiJudgement();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('validator')) {
                obj['validator'] = ApiClient.convertToType(data['validator'], 'String');
            }
            if (data.hasOwnProperty('verdict')) {
                obj['verdict'] = ApiVerdictStatus.constructFromObject(data['verdict']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiJudgement</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiJudgement</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiJudgement.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['validator'] && !(typeof data['validator'] === 'string' || data['validator'] instanceof String)) {
            throw new Error("Expected the field `validator` to be a primitive type in the JSON string but got " + data['validator']);
        }

        return true;
    }


}

ApiJudgement.RequiredProperties = ["token", "validator", "verdict"];

/**
 * @member {String} token
 */
ApiJudgement.prototype['token'] = undefined;

/**
 * @member {String} validator
 */
ApiJudgement.prototype['validator'] = undefined;

/**
 * @member {module:model/ApiVerdictStatus} verdict
 */
ApiJudgement.prototype['verdict'] = undefined;






export default ApiJudgement;

