/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApiMediaType.
* @enum {}
* @readonly
*/
export default class ApiMediaType {
    
        /**
         * value: "IMAGE"
         * @const
         */
        "IMAGE" = "IMAGE";

    
        /**
         * value: "VIDEO"
         * @const
         */
        "VIDEO" = "VIDEO";

    
        /**
         * value: "TEXT"
         * @const
         */
        "TEXT" = "TEXT";

    

    /**
    * Returns a <code>ApiMediaType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApiMediaType} The enum <code>ApiMediaType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

