/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiMediaCollection model module.
 * @module model/ApiMediaCollection
 * @version 2.0.0-RC4
 */
class ApiMediaCollection {
    /**
     * Constructs a new <code>ApiMediaCollection</code>.
     * @alias module:model/ApiMediaCollection
     * @param name {String} 
     * @param itemCount {Number} 
     */
    constructor(name, itemCount) { 
        
        ApiMediaCollection.initialize(this, name, itemCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, itemCount) { 
        obj['name'] = name;
        obj['itemCount'] = itemCount;
    }

    /**
     * Constructs a <code>ApiMediaCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiMediaCollection} obj Optional instance to populate.
     * @return {module:model/ApiMediaCollection} The populated <code>ApiMediaCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiMediaCollection();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('basePath')) {
                obj['basePath'] = ApiClient.convertToType(data['basePath'], 'String');
            }
            if (data.hasOwnProperty('itemCount')) {
                obj['itemCount'] = ApiClient.convertToType(data['itemCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiMediaCollection</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiMediaCollection</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiMediaCollection.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['basePath'] && !(typeof data['basePath'] === 'string' || data['basePath'] instanceof String)) {
            throw new Error("Expected the field `basePath` to be a primitive type in the JSON string but got " + data['basePath']);
        }

        return true;
    }


}

ApiMediaCollection.RequiredProperties = ["name", "itemCount"];

/**
 * @member {String} id
 */
ApiMediaCollection.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ApiMediaCollection.prototype['name'] = undefined;

/**
 * @member {String} description
 */
ApiMediaCollection.prototype['description'] = undefined;

/**
 * @member {String} basePath
 */
ApiMediaCollection.prototype['basePath'] = undefined;

/**
 * @member {Number} itemCount
 */
ApiMediaCollection.prototype['itemCount'] = undefined;






export default ApiMediaCollection;

