/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiMediaCollection from './ApiMediaCollection';
import ApiMediaItem from './ApiMediaItem';

/**
 * The ApiPopulatedMediaCollection model module.
 * @module model/ApiPopulatedMediaCollection
 * @version 2.0.0-RC4
 */
class ApiPopulatedMediaCollection {
    /**
     * Constructs a new <code>ApiPopulatedMediaCollection</code>.
     * @alias module:model/ApiPopulatedMediaCollection
     * @param collection {module:model/ApiMediaCollection} 
     * @param items {Array.<module:model/ApiMediaItem>} 
     */
    constructor(collection, items) { 
        
        ApiPopulatedMediaCollection.initialize(this, collection, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, collection, items) { 
        obj['collection'] = collection;
        obj['items'] = items;
    }

    /**
     * Constructs a <code>ApiPopulatedMediaCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiPopulatedMediaCollection} obj Optional instance to populate.
     * @return {module:model/ApiPopulatedMediaCollection} The populated <code>ApiPopulatedMediaCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiPopulatedMediaCollection();

            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiMediaCollection.constructFromObject(data['collection']);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [ApiMediaItem]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiPopulatedMediaCollection</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiPopulatedMediaCollection</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiPopulatedMediaCollection.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `collection`
        if (data['collection']) { // data not null
          ApiMediaCollection.validateJSON(data['collection']);
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                ApiMediaItem.validateJSON(item);
            };
        }

        return true;
    }


}

ApiPopulatedMediaCollection.RequiredProperties = ["collection", "items"];

/**
 * @member {module:model/ApiMediaCollection} collection
 */
ApiPopulatedMediaCollection.prototype['collection'] = undefined;

/**
 * @member {Array.<module:model/ApiMediaItem>} items
 */
ApiPopulatedMediaCollection.prototype['items'] = undefined;






export default ApiPopulatedMediaCollection;

