/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiRunProperties model module.
 * @module model/ApiRunProperties
 * @version 2.0.0-RC4
 */
class ApiRunProperties {
    /**
     * Constructs a new <code>ApiRunProperties</code>.
     * @alias module:model/ApiRunProperties
     * @param participantCanView {Boolean} 
     * @param shuffleTasks {Boolean} 
     * @param allowRepeatedTasks {Boolean} 
     * @param limitSubmissionPreviews {Number} 
     */
    constructor(participantCanView, shuffleTasks, allowRepeatedTasks, limitSubmissionPreviews) { 
        
        ApiRunProperties.initialize(this, participantCanView, shuffleTasks, allowRepeatedTasks, limitSubmissionPreviews);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, participantCanView, shuffleTasks, allowRepeatedTasks, limitSubmissionPreviews) { 
        obj['participantCanView'] = participantCanView;
        obj['shuffleTasks'] = shuffleTasks;
        obj['allowRepeatedTasks'] = allowRepeatedTasks;
        obj['limitSubmissionPreviews'] = limitSubmissionPreviews;
    }

    /**
     * Constructs a <code>ApiRunProperties</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiRunProperties} obj Optional instance to populate.
     * @return {module:model/ApiRunProperties} The populated <code>ApiRunProperties</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiRunProperties();

            if (data.hasOwnProperty('participantCanView')) {
                obj['participantCanView'] = ApiClient.convertToType(data['participantCanView'], 'Boolean');
            }
            if (data.hasOwnProperty('shuffleTasks')) {
                obj['shuffleTasks'] = ApiClient.convertToType(data['shuffleTasks'], 'Boolean');
            }
            if (data.hasOwnProperty('allowRepeatedTasks')) {
                obj['allowRepeatedTasks'] = ApiClient.convertToType(data['allowRepeatedTasks'], 'Boolean');
            }
            if (data.hasOwnProperty('limitSubmissionPreviews')) {
                obj['limitSubmissionPreviews'] = ApiClient.convertToType(data['limitSubmissionPreviews'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiRunProperties</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiRunProperties</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiRunProperties.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ApiRunProperties.RequiredProperties = ["participantCanView", "shuffleTasks", "allowRepeatedTasks", "limitSubmissionPreviews"];

/**
 * @member {Boolean} participantCanView
 */
ApiRunProperties.prototype['participantCanView'] = undefined;

/**
 * @member {Boolean} shuffleTasks
 */
ApiRunProperties.prototype['shuffleTasks'] = undefined;

/**
 * @member {Boolean} allowRepeatedTasks
 */
ApiRunProperties.prototype['allowRepeatedTasks'] = undefined;

/**
 * @member {Number} limitSubmissionPreviews
 */
ApiRunProperties.prototype['limitSubmissionPreviews'] = undefined;






export default ApiRunProperties;

