/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApiRole.
* @enum {}
* @readonly
*/
export default class ApiRole {
    
        /**
         * value: "ANYONE"
         * @const
         */
        "ANYONE" = "ANYONE";

    
        /**
         * value: "VIEWER"
         * @const
         */
        "VIEWER" = "VIEWER";

    
        /**
         * value: "PARTICIPANT"
         * @const
         */
        "PARTICIPANT" = "PARTICIPANT";

    
        /**
         * value: "JUDGE"
         * @const
         */
        "JUDGE" = "JUDGE";

    
        /**
         * value: "ADMIN"
         * @const
         */
        "ADMIN" = "ADMIN";

    

    /**
    * Returns a <code>ApiRole</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApiRole} The enum <code>ApiRole</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

