/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiScoreSeriesPoint model module.
 * @module model/ApiScoreSeriesPoint
 * @version 2.0.0-RC4
 */
class ApiScoreSeriesPoint {
    /**
     * Constructs a new <code>ApiScoreSeriesPoint</code>.
     * @alias module:model/ApiScoreSeriesPoint
     * @param score {Number} 
     * @param timestamp {Number} 
     */
    constructor(score, timestamp) { 
        
        ApiScoreSeriesPoint.initialize(this, score, timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, score, timestamp) { 
        obj['score'] = score;
        obj['timestamp'] = timestamp;
    }

    /**
     * Constructs a <code>ApiScoreSeriesPoint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiScoreSeriesPoint} obj Optional instance to populate.
     * @return {module:model/ApiScoreSeriesPoint} The populated <code>ApiScoreSeriesPoint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiScoreSeriesPoint();

            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiScoreSeriesPoint</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiScoreSeriesPoint</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiScoreSeriesPoint.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ApiScoreSeriesPoint.RequiredProperties = ["score", "timestamp"];

/**
 * @member {Number} score
 */
ApiScoreSeriesPoint.prototype['score'] = undefined;

/**
 * @member {Number} timestamp
 */
ApiScoreSeriesPoint.prototype['timestamp'] = undefined;






export default ApiScoreSeriesPoint;

