/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiSubmission from './ApiSubmission';

/**
 * The ApiSubmissionInfo model module.
 * @module model/ApiSubmissionInfo
 * @version 2.0.0-RC4
 */
class ApiSubmissionInfo {
    /**
     * Constructs a new <code>ApiSubmissionInfo</code>.
     * @alias module:model/ApiSubmissionInfo
     * @param evaluationId {String} 
     * @param taskId {String} 
     * @param submissions {Array.<module:model/ApiSubmission>} 
     */
    constructor(evaluationId, taskId, submissions) { 
        
        ApiSubmissionInfo.initialize(this, evaluationId, taskId, submissions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, evaluationId, taskId, submissions) { 
        obj['evaluationId'] = evaluationId;
        obj['taskId'] = taskId;
        obj['submissions'] = submissions;
    }

    /**
     * Constructs a <code>ApiSubmissionInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiSubmissionInfo} obj Optional instance to populate.
     * @return {module:model/ApiSubmissionInfo} The populated <code>ApiSubmissionInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiSubmissionInfo();

            if (data.hasOwnProperty('evaluationId')) {
                obj['evaluationId'] = ApiClient.convertToType(data['evaluationId'], 'String');
            }
            if (data.hasOwnProperty('taskId')) {
                obj['taskId'] = ApiClient.convertToType(data['taskId'], 'String');
            }
            if (data.hasOwnProperty('submissions')) {
                obj['submissions'] = ApiClient.convertToType(data['submissions'], [ApiSubmission]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiSubmissionInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiSubmissionInfo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiSubmissionInfo.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['evaluationId'] && !(typeof data['evaluationId'] === 'string' || data['evaluationId'] instanceof String)) {
            throw new Error("Expected the field `evaluationId` to be a primitive type in the JSON string but got " + data['evaluationId']);
        }
        // ensure the json data is a string
        if (data['taskId'] && !(typeof data['taskId'] === 'string' || data['taskId'] instanceof String)) {
            throw new Error("Expected the field `taskId` to be a primitive type in the JSON string but got " + data['taskId']);
        }
        if (data['submissions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['submissions'])) {
                throw new Error("Expected the field `submissions` to be an array in the JSON data but got " + data['submissions']);
            }
            // validate the optional field `submissions` (array)
            for (const item of data['submissions']) {
                ApiSubmission.validateJSON(item);
            };
        }

        return true;
    }


}

ApiSubmissionInfo.RequiredProperties = ["evaluationId", "taskId", "submissions"];

/**
 * @member {String} evaluationId
 */
ApiSubmissionInfo.prototype['evaluationId'] = undefined;

/**
 * @member {String} taskId
 */
ApiSubmissionInfo.prototype['taskId'] = undefined;

/**
 * @member {Array.<module:model/ApiSubmission>} submissions
 */
ApiSubmissionInfo.prototype['submissions'] = undefined;






export default ApiSubmissionInfo;

