/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiScoreSeriesPoint from './ApiScoreSeriesPoint';

/**
 * The ApiScoreSeries model module.
 * @module model/ApiScoreSeries
 * @version 2.0.0-RC4
 */
class ApiScoreSeries {
    /**
     * Constructs a new <code>ApiScoreSeries</code>.
     * @alias module:model/ApiScoreSeries
     * @param team {String} 
     * @param name {String} 
     * @param points {Array.<module:model/ApiScoreSeriesPoint>} 
     */
    constructor(team, name, points) { 
        
        ApiScoreSeries.initialize(this, team, name, points);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, team, name, points) { 
        obj['team'] = team;
        obj['name'] = name;
        obj['points'] = points;
    }

    /**
     * Constructs a <code>ApiScoreSeries</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiScoreSeries} obj Optional instance to populate.
     * @return {module:model/ApiScoreSeries} The populated <code>ApiScoreSeries</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiScoreSeries();

            if (data.hasOwnProperty('team')) {
                obj['team'] = ApiClient.convertToType(data['team'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('points')) {
                obj['points'] = ApiClient.convertToType(data['points'], [ApiScoreSeriesPoint]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiScoreSeries</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiScoreSeries</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiScoreSeries.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['team'] && !(typeof data['team'] === 'string' || data['team'] instanceof String)) {
            throw new Error("Expected the field `team` to be a primitive type in the JSON string but got " + data['team']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['points']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['points'])) {
                throw new Error("Expected the field `points` to be an array in the JSON data but got " + data['points']);
            }
            // validate the optional field `points` (array)
            for (const item of data['points']) {
                ApiScoreSeriesPoint.validateJSON(item);
            };
        }

        return true;
    }


}

ApiScoreSeries.RequiredProperties = ["team", "name", "points"];

/**
 * @member {String} team
 */
ApiScoreSeries.prototype['team'] = undefined;

/**
 * @member {String} name
 */
ApiScoreSeries.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/ApiScoreSeriesPoint>} points
 */
ApiScoreSeries.prototype['points'] = undefined;






export default ApiScoreSeries;

