/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApiSubmissionOption.
* @enum {}
* @readonly
*/
export default class ApiSubmissionOption {
    
        /**
         * value: "NO_DUPLICATES"
         * @const
         */
        "NO_DUPLICATES" = "NO_DUPLICATES";

    
        /**
         * value: "LIMIT_CORRECT_PER_TEAM"
         * @const
         */
        "LIMIT_CORRECT_PER_TEAM" = "LIMIT_CORRECT_PER_TEAM";

    
        /**
         * value: "LIMIT_WRONG_PER_TEAM"
         * @const
         */
        "LIMIT_WRONG_PER_TEAM" = "LIMIT_WRONG_PER_TEAM";

    
        /**
         * value: "LIMIT_TOTAL_PER_TEAM"
         * @const
         */
        "LIMIT_TOTAL_PER_TEAM" = "LIMIT_TOTAL_PER_TEAM";

    
        /**
         * value: "LIMIT_CORRECT_PER_MEMBER"
         * @const
         */
        "LIMIT_CORRECT_PER_MEMBER" = "LIMIT_CORRECT_PER_MEMBER";

    
        /**
         * value: "TEMPORAL_SUBMISSION"
         * @const
         */
        "TEMPORAL_SUBMISSION" = "TEMPORAL_SUBMISSION";

    
        /**
         * value: "TEXTUAL_SUBMISSION"
         * @const
         */
        "TEXTUAL_SUBMISSION" = "TEXTUAL_SUBMISSION";

    
        /**
         * value: "ITEM_SUBMISSION"
         * @const
         */
        "ITEM_SUBMISSION" = "ITEM_SUBMISSION";

    
        /**
         * value: "MINIMUM_TIME_GAP"
         * @const
         */
        "MINIMUM_TIME_GAP" = "MINIMUM_TIME_GAP";

    

    /**
    * Returns a <code>ApiSubmissionOption</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApiSubmissionOption} The enum <code>ApiSubmissionOption</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

