/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiTaskOverview from './ApiTaskOverview';

/**
 * The ApiTeamTaskOverview model module.
 * @module model/ApiTeamTaskOverview
 * @version 2.0.0-RC4
 */
class ApiTeamTaskOverview {
    /**
     * Constructs a new <code>ApiTeamTaskOverview</code>.
     * @alias module:model/ApiTeamTaskOverview
     * @param teamId {String} 
     * @param tasks {Array.<module:model/ApiTaskOverview>} 
     */
    constructor(teamId, tasks) { 
        
        ApiTeamTaskOverview.initialize(this, teamId, tasks);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, teamId, tasks) { 
        obj['teamId'] = teamId;
        obj['tasks'] = tasks;
    }

    /**
     * Constructs a <code>ApiTeamTaskOverview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTeamTaskOverview} obj Optional instance to populate.
     * @return {module:model/ApiTeamTaskOverview} The populated <code>ApiTeamTaskOverview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTeamTaskOverview();

            if (data.hasOwnProperty('teamId')) {
                obj['teamId'] = ApiClient.convertToType(data['teamId'], 'String');
            }
            if (data.hasOwnProperty('tasks')) {
                obj['tasks'] = ApiClient.convertToType(data['tasks'], [ApiTaskOverview]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTeamTaskOverview</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTeamTaskOverview</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiTeamTaskOverview.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['teamId'] && !(typeof data['teamId'] === 'string' || data['teamId'] instanceof String)) {
            throw new Error("Expected the field `teamId` to be a primitive type in the JSON string but got " + data['teamId']);
        }
        if (data['tasks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['tasks'])) {
                throw new Error("Expected the field `tasks` to be an array in the JSON data but got " + data['tasks']);
            }
            // validate the optional field `tasks` (array)
            for (const item of data['tasks']) {
                ApiTaskOverview.validateJSON(item);
            };
        }

        return true;
    }


}

ApiTeamTaskOverview.RequiredProperties = ["teamId", "tasks"];

/**
 * @member {String} teamId
 */
ApiTeamTaskOverview.prototype['teamId'] = undefined;

/**
 * @member {Array.<module:model/ApiTaskOverview>} tasks
 */
ApiTeamTaskOverview.prototype['tasks'] = undefined;






export default ApiTeamTaskOverview;

