/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApiTaskStatus.
* @enum {}
* @readonly
*/
export default class ApiTaskStatus {
    
        /**
         * value: "NO_TASK"
         * @const
         */
        "NO_TASK" = "NO_TASK";

    
        /**
         * value: "CREATED"
         * @const
         */
        "CREATED" = "CREATED";

    
        /**
         * value: "PREPARING"
         * @const
         */
        "PREPARING" = "PREPARING";

    
        /**
         * value: "RUNNING"
         * @const
         */
        "RUNNING" = "RUNNING";

    
        /**
         * value: "ENDED"
         * @const
         */
        "ENDED" = "ENDED";

    
        /**
         * value: "IGNORED"
         * @const
         */
        "IGNORED" = "IGNORED";

    

    /**
    * Returns a <code>ApiTaskStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApiTaskStatus} The enum <code>ApiTaskStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

