/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiContentElement from './ApiContentElement';

/**
 * The ApiTargetContent model module.
 * @module model/ApiTargetContent
 * @version 2.0.0-RC4
 */
class ApiTargetContent {
    /**
     * Constructs a new <code>ApiTargetContent</code>.
     * @alias module:model/ApiTargetContent
     * @param taskId {String} 
     * @param sequence {Array.<module:model/ApiContentElement>} 
     */
    constructor(taskId, sequence) { 
        
        ApiTargetContent.initialize(this, taskId, sequence);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, taskId, sequence) { 
        obj['taskId'] = taskId;
        obj['sequence'] = sequence;
    }

    /**
     * Constructs a <code>ApiTargetContent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTargetContent} obj Optional instance to populate.
     * @return {module:model/ApiTargetContent} The populated <code>ApiTargetContent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTargetContent();

            if (data.hasOwnProperty('taskId')) {
                obj['taskId'] = ApiClient.convertToType(data['taskId'], 'String');
            }
            if (data.hasOwnProperty('sequence')) {
                obj['sequence'] = ApiClient.convertToType(data['sequence'], [ApiContentElement]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTargetContent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTargetContent</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiTargetContent.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['taskId'] && !(typeof data['taskId'] === 'string' || data['taskId'] instanceof String)) {
            throw new Error("Expected the field `taskId` to be a primitive type in the JSON string but got " + data['taskId']);
        }
        if (data['sequence']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['sequence'])) {
                throw new Error("Expected the field `sequence` to be an array in the JSON data but got " + data['sequence']);
            }
            // validate the optional field `sequence` (array)
            for (const item of data['sequence']) {
                ApiContentElement.validateJSON(item);
            };
        }

        return true;
    }


}

ApiTargetContent.RequiredProperties = ["taskId", "sequence"];

/**
 * @member {String} taskId
 */
ApiTargetContent.prototype['taskId'] = undefined;

/**
 * @member {Array.<module:model/ApiContentElement>} sequence
 */
ApiTargetContent.prototype['sequence'] = undefined;






export default ApiTargetContent;

