/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiTargetType from './ApiTargetType';
import ApiTemporalRange from './ApiTemporalRange';

/**
 * The ApiTarget model module.
 * @module model/ApiTarget
 * @version 2.0.0-RC4
 */
class ApiTarget {
    /**
     * Constructs a new <code>ApiTarget</code>.
     * @alias module:model/ApiTarget
     * @param type {module:model/ApiTargetType} 
     */
    constructor(type) { 
        
        ApiTarget.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>ApiTarget</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTarget} obj Optional instance to populate.
     * @return {module:model/ApiTarget} The populated <code>ApiTarget</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTarget();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiTargetType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
            if (data.hasOwnProperty('range')) {
                obj['range'] = ApiTemporalRange.constructFromObject(data['range']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTarget</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTarget</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiTarget.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['target'] && !(typeof data['target'] === 'string' || data['target'] instanceof String)) {
            throw new Error("Expected the field `target` to be a primitive type in the JSON string but got " + data['target']);
        }
        // validate the optional field `range`
        if (data['range']) { // data not null
          ApiTemporalRange.validateJSON(data['range']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

ApiTarget.RequiredProperties = ["type"];

/**
 * @member {module:model/ApiTargetType} type
 */
ApiTarget.prototype['type'] = undefined;

/**
 * @member {String} target
 */
ApiTarget.prototype['target'] = undefined;

/**
 * @member {module:model/ApiTemporalRange} range
 */
ApiTarget.prototype['range'] = undefined;

/**
 * @member {String} name
 */
ApiTarget.prototype['name'] = undefined;






export default ApiTarget;

