/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiTeam from './ApiTeam';
import ApiTeamAggregatorType from './ApiTeamAggregatorType';

/**
 * The ApiTeamGroup model module.
 * @module model/ApiTeamGroup
 * @version 2.0.0-RC4
 */
class ApiTeamGroup {
    /**
     * Constructs a new <code>ApiTeamGroup</code>.
     * @alias module:model/ApiTeamGroup
     * @param teams {Array.<module:model/ApiTeam>} 
     * @param aggregation {module:model/ApiTeamAggregatorType} 
     */
    constructor(teams, aggregation) { 
        
        ApiTeamGroup.initialize(this, teams, aggregation);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, teams, aggregation) { 
        obj['teams'] = teams;
        obj['aggregation'] = aggregation;
    }

    /**
     * Constructs a <code>ApiTeamGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTeamGroup} obj Optional instance to populate.
     * @return {module:model/ApiTeamGroup} The populated <code>ApiTeamGroup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTeamGroup();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('teams')) {
                obj['teams'] = ApiClient.convertToType(data['teams'], [ApiTeam]);
            }
            if (data.hasOwnProperty('aggregation')) {
                obj['aggregation'] = ApiTeamAggregatorType.constructFromObject(data['aggregation']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTeamGroup</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTeamGroup</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiTeamGroup.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['teams']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['teams'])) {
                throw new Error("Expected the field `teams` to be an array in the JSON data but got " + data['teams']);
            }
            // validate the optional field `teams` (array)
            for (const item of data['teams']) {
                ApiTeam.validateJSON(item);
            };
        }

        return true;
    }


}

ApiTeamGroup.RequiredProperties = ["teams", "aggregation"];

/**
 * @member {String} id
 */
ApiTeamGroup.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ApiTeamGroup.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/ApiTeam>} teams
 */
ApiTeamGroup.prototype['teams'] = undefined;

/**
 * @member {module:model/ApiTeamAggregatorType} aggregation
 */
ApiTeamGroup.prototype['aggregation'] = undefined;






export default ApiTeamGroup;

