/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApiTargetType.
* @enum {}
* @readonly
*/
export default class ApiTargetType {
    
        /**
         * value: "JUDGEMENT"
         * @const
         */
        "JUDGEMENT" = "JUDGEMENT";

    
        /**
         * value: "JUDGEMENT_WITH_VOTE"
         * @const
         */
        "JUDGEMENT_WITH_VOTE" = "JUDGEMENT_WITH_VOTE";

    
        /**
         * value: "MEDIA_ITEM"
         * @const
         */
        "MEDIA_ITEM" = "MEDIA_ITEM";

    
        /**
         * value: "MEDIA_ITEM_TEMPORAL_RANGE"
         * @const
         */
        "MEDIA_ITEM_TEMPORAL_RANGE" = "MEDIA_ITEM_TEMPORAL_RANGE";

    
        /**
         * value: "TEXT"
         * @const
         */
        "TEXT" = "TEXT";

    

    /**
    * Returns a <code>ApiTargetType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApiTargetType} The enum <code>ApiTargetType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

