/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApiTargetOption.
* @enum {}
* @readonly
*/
export default class ApiTargetOption {
    
        /**
         * value: "SINGLE_MEDIA_ITEM"
         * @const
         */
        "SINGLE_MEDIA_ITEM" = "SINGLE_MEDIA_ITEM";

    
        /**
         * value: "SINGLE_MEDIA_SEGMENT"
         * @const
         */
        "SINGLE_MEDIA_SEGMENT" = "SINGLE_MEDIA_SEGMENT";

    
        /**
         * value: "JUDGEMENT"
         * @const
         */
        "JUDGEMENT" = "JUDGEMENT";

    
        /**
         * value: "VOTE"
         * @const
         */
        "VOTE" = "VOTE";

    
        /**
         * value: "TEXT"
         * @const
         */
        "TEXT" = "TEXT";

    

    /**
    * Returns a <code>ApiTargetOption</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApiTargetOption} The enum <code>ApiTargetOption</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

