/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiTemporalUnit from './ApiTemporalUnit';

/**
 * The ApiTemporalPoint model module.
 * @module model/ApiTemporalPoint
 * @version 2.0.0-RC4
 */
class ApiTemporalPoint {
    /**
     * Constructs a new <code>ApiTemporalPoint</code>.
     * @alias module:model/ApiTemporalPoint
     * @param value {String} 
     * @param unit {module:model/ApiTemporalUnit} 
     */
    constructor(value, unit) { 
        
        ApiTemporalPoint.initialize(this, value, unit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, value, unit) { 
        obj['value'] = value;
        obj['unit'] = unit;
    }

    /**
     * Constructs a <code>ApiTemporalPoint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTemporalPoint} obj Optional instance to populate.
     * @return {module:model/ApiTemporalPoint} The populated <code>ApiTemporalPoint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTemporalPoint();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiTemporalUnit.constructFromObject(data['unit']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTemporalPoint</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTemporalPoint</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiTemporalPoint.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }


}

ApiTemporalPoint.RequiredProperties = ["value", "unit"];

/**
 * @member {String} value
 */
ApiTemporalPoint.prototype['value'] = undefined;

/**
 * @member {module:model/ApiTemporalUnit} unit
 */
ApiTemporalPoint.prototype['unit'] = undefined;






export default ApiTemporalPoint;

