/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApiTaskOption.
* @enum {}
* @readonly
*/
export default class ApiTaskOption {
    
        /**
         * value: "HIDDEN_RESULTS"
         * @const
         */
        "HIDDEN_RESULTS" = "HIDDEN_RESULTS";

    
        /**
         * value: "MAP_TO_SEGMENT"
         * @const
         */
        "MAP_TO_SEGMENT" = "MAP_TO_SEGMENT";

    
        /**
         * value: "PROLONG_ON_SUBMISSION"
         * @const
         */
        "PROLONG_ON_SUBMISSION" = "PROLONG_ON_SUBMISSION";

    

    /**
    * Returns a <code>ApiTaskOption</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApiTaskOption} The enum <code>ApiTaskOption</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

