/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiTaskStatus from './ApiTaskStatus';

/**
 * The ApiTaskOverview model module.
 * @module model/ApiTaskOverview
 * @version 2.0.0-RC4
 */
class ApiTaskOverview {
    /**
     * Constructs a new <code>ApiTaskOverview</code>.
     * @alias module:model/ApiTaskOverview
     * @param id {String} 
     * @param name {String} 
     * @param type {String} 
     * @param group {String} 
     * @param duration {Number} 
     * @param taskId {String} 
     * @param status {module:model/ApiTaskStatus} 
     */
    constructor(id, name, type, group, duration, taskId, status) { 
        
        ApiTaskOverview.initialize(this, id, name, type, group, duration, taskId, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, type, group, duration, taskId, status) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['type'] = type;
        obj['group'] = group;
        obj['duration'] = duration;
        obj['taskId'] = taskId;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>ApiTaskOverview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTaskOverview} obj Optional instance to populate.
     * @return {module:model/ApiTaskOverview} The populated <code>ApiTaskOverview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTaskOverview();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('group')) {
                obj['group'] = ApiClient.convertToType(data['group'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('taskId')) {
                obj['taskId'] = ApiClient.convertToType(data['taskId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiTaskStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('started')) {
                obj['started'] = ApiClient.convertToType(data['started'], 'Number');
            }
            if (data.hasOwnProperty('ended')) {
                obj['ended'] = ApiClient.convertToType(data['ended'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTaskOverview</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTaskOverview</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiTaskOverview.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['group'] && !(typeof data['group'] === 'string' || data['group'] instanceof String)) {
            throw new Error("Expected the field `group` to be a primitive type in the JSON string but got " + data['group']);
        }
        // ensure the json data is a string
        if (data['taskId'] && !(typeof data['taskId'] === 'string' || data['taskId'] instanceof String)) {
            throw new Error("Expected the field `taskId` to be a primitive type in the JSON string but got " + data['taskId']);
        }

        return true;
    }


}

ApiTaskOverview.RequiredProperties = ["id", "name", "type", "group", "duration", "taskId", "status"];

/**
 * @member {String} id
 */
ApiTaskOverview.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ApiTaskOverview.prototype['name'] = undefined;

/**
 * @member {String} type
 */
ApiTaskOverview.prototype['type'] = undefined;

/**
 * @member {String} group
 */
ApiTaskOverview.prototype['group'] = undefined;

/**
 * @member {Number} duration
 */
ApiTaskOverview.prototype['duration'] = undefined;

/**
 * @member {String} taskId
 */
ApiTaskOverview.prototype['taskId'] = undefined;

/**
 * @member {module:model/ApiTaskStatus} status
 */
ApiTaskOverview.prototype['status'] = undefined;

/**
 * @member {Number} started
 */
ApiTaskOverview.prototype['started'] = undefined;

/**
 * @member {Number} ended
 */
ApiTaskOverview.prototype['ended'] = undefined;






export default ApiTaskOverview;

