/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiTaskTemplateInfo model module.
 * @module model/ApiTaskTemplateInfo
 * @version 2.0.0-RC4
 */
class ApiTaskTemplateInfo {
    /**
     * Constructs a new <code>ApiTaskTemplateInfo</code>.
     * @alias module:model/ApiTaskTemplateInfo
     * @param templateId {String} 
     * @param name {String} 
     * @param taskGroup {String} 
     * @param taskType {String} 
     * @param duration {Number} 
     */
    constructor(templateId, name, taskGroup, taskType, duration) { 
        
        ApiTaskTemplateInfo.initialize(this, templateId, name, taskGroup, taskType, duration);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, templateId, name, taskGroup, taskType, duration) { 
        obj['templateId'] = templateId;
        obj['name'] = name;
        obj['taskGroup'] = taskGroup;
        obj['taskType'] = taskType;
        obj['duration'] = duration;
    }

    /**
     * Constructs a <code>ApiTaskTemplateInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTaskTemplateInfo} obj Optional instance to populate.
     * @return {module:model/ApiTaskTemplateInfo} The populated <code>ApiTaskTemplateInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTaskTemplateInfo();

            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('taskGroup')) {
                obj['taskGroup'] = ApiClient.convertToType(data['taskGroup'], 'String');
            }
            if (data.hasOwnProperty('taskType')) {
                obj['taskType'] = ApiClient.convertToType(data['taskType'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTaskTemplateInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTaskTemplateInfo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiTaskTemplateInfo.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['templateId'] && !(typeof data['templateId'] === 'string' || data['templateId'] instanceof String)) {
            throw new Error("Expected the field `templateId` to be a primitive type in the JSON string but got " + data['templateId']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['comment'] && !(typeof data['comment'] === 'string' || data['comment'] instanceof String)) {
            throw new Error("Expected the field `comment` to be a primitive type in the JSON string but got " + data['comment']);
        }
        // ensure the json data is a string
        if (data['taskGroup'] && !(typeof data['taskGroup'] === 'string' || data['taskGroup'] instanceof String)) {
            throw new Error("Expected the field `taskGroup` to be a primitive type in the JSON string but got " + data['taskGroup']);
        }
        // ensure the json data is a string
        if (data['taskType'] && !(typeof data['taskType'] === 'string' || data['taskType'] instanceof String)) {
            throw new Error("Expected the field `taskType` to be a primitive type in the JSON string but got " + data['taskType']);
        }

        return true;
    }


}

ApiTaskTemplateInfo.RequiredProperties = ["templateId", "name", "taskGroup", "taskType", "duration"];

/**
 * @member {String} templateId
 */
ApiTaskTemplateInfo.prototype['templateId'] = undefined;

/**
 * @member {String} name
 */
ApiTaskTemplateInfo.prototype['name'] = undefined;

/**
 * @member {String} comment
 */
ApiTaskTemplateInfo.prototype['comment'] = undefined;

/**
 * @member {String} taskGroup
 */
ApiTaskTemplateInfo.prototype['taskGroup'] = undefined;

/**
 * @member {String} taskType
 */
ApiTaskTemplateInfo.prototype['taskType'] = undefined;

/**
 * @member {Number} duration
 */
ApiTaskTemplateInfo.prototype['duration'] = undefined;






export default ApiTaskTemplateInfo;

