/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiVerdictStatus from './ApiVerdictStatus';

/**
 * The ApiVote model module.
 * @module model/ApiVote
 * @version 2.0.0-RC4
 */
class ApiVote {
    /**
     * Constructs a new <code>ApiVote</code>.
     * @alias module:model/ApiVote
     * @param verdict {module:model/ApiVerdictStatus} 
     */
    constructor(verdict) { 
        
        ApiVote.initialize(this, verdict);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, verdict) { 
        obj['verdict'] = verdict;
    }

    /**
     * Constructs a <code>ApiVote</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiVote} obj Optional instance to populate.
     * @return {module:model/ApiVote} The populated <code>ApiVote</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiVote();

            if (data.hasOwnProperty('verdict')) {
                obj['verdict'] = ApiVerdictStatus.constructFromObject(data['verdict']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiVote</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiVote</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiVote.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ApiVote.RequiredProperties = ["verdict"];

/**
 * @member {module:model/ApiVerdictStatus} verdict
 */
ApiVote.prototype['verdict'] = undefined;






export default ApiVote;

