/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiViewerInfo model module.
 * @module model/ApiViewerInfo
 * @version 2.0.0-RC4
 */
class ApiViewerInfo {
    /**
     * Constructs a new <code>ApiViewerInfo</code>.
     * @alias module:model/ApiViewerInfo
     * @param viewersId {String} 
     * @param username {String} 
     * @param host {String} 
     * @param ready {Boolean} 
     */
    constructor(viewersId, username, host, ready) { 
        
        ApiViewerInfo.initialize(this, viewersId, username, host, ready);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, viewersId, username, host, ready) { 
        obj['viewersId'] = viewersId;
        obj['username'] = username;
        obj['host'] = host;
        obj['ready'] = ready;
    }

    /**
     * Constructs a <code>ApiViewerInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiViewerInfo} obj Optional instance to populate.
     * @return {module:model/ApiViewerInfo} The populated <code>ApiViewerInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiViewerInfo();

            if (data.hasOwnProperty('viewersId')) {
                obj['viewersId'] = ApiClient.convertToType(data['viewersId'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
            if (data.hasOwnProperty('ready')) {
                obj['ready'] = ApiClient.convertToType(data['ready'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiViewerInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiViewerInfo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiViewerInfo.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['viewersId'] && !(typeof data['viewersId'] === 'string' || data['viewersId'] instanceof String)) {
            throw new Error("Expected the field `viewersId` to be a primitive type in the JSON string but got " + data['viewersId']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['host'] && !(typeof data['host'] === 'string' || data['host'] instanceof String)) {
            throw new Error("Expected the field `host` to be a primitive type in the JSON string but got " + data['host']);
        }

        return true;
    }


}

ApiViewerInfo.RequiredProperties = ["viewersId", "username", "host", "ready"];

/**
 * @member {String} viewersId
 */
ApiViewerInfo.prototype['viewersId'] = undefined;

/**
 * @member {String} username
 */
ApiViewerInfo.prototype['username'] = undefined;

/**
 * @member {String} host
 */
ApiViewerInfo.prototype['host'] = undefined;

/**
 * @member {Boolean} ready
 */
ApiViewerInfo.prototype['ready'] = undefined;






export default ApiViewerInfo;

