/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApiVerdictStatus.
* @enum {}
* @readonly
*/
export default class ApiVerdictStatus {
    
        /**
         * value: "CORRECT"
         * @const
         */
        "CORRECT" = "CORRECT";

    
        /**
         * value: "WRONG"
         * @const
         */
        "WRONG" = "WRONG";

    
        /**
         * value: "INDETERMINATE"
         * @const
         */
        "INDETERMINATE" = "INDETERMINATE";

    
        /**
         * value: "UNDECIDABLE"
         * @const
         */
        "UNDECIDABLE" = "UNDECIDABLE";

    

    /**
    * Returns a <code>ApiVerdictStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApiVerdictStatus} The enum <code>ApiVerdictStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

