/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import QueryEvent from './QueryEvent';

/**
 * The QueryEventLog model module.
 * @module model/QueryEventLog
 * @version 2.0.0-RC4
 */
class QueryEventLog {
    /**
     * Constructs a new <code>QueryEventLog</code>.
     * @alias module:model/QueryEventLog
     * @param timestamp {Number} 
     * @param events {Array.<module:model/QueryEvent>} 
     */
    constructor(timestamp, events) { 
        
        QueryEventLog.initialize(this, timestamp, events);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, timestamp, events) { 
        obj['timestamp'] = timestamp;
        obj['events'] = events;
    }

    /**
     * Constructs a <code>QueryEventLog</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryEventLog} obj Optional instance to populate.
     * @return {module:model/QueryEventLog} The populated <code>QueryEventLog</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryEventLog();

            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [QueryEvent]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QueryEventLog</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QueryEventLog</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QueryEventLog.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['events']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['events'])) {
                throw new Error("Expected the field `events` to be an array in the JSON data but got " + data['events']);
            }
            // validate the optional field `events` (array)
            for (const item of data['events']) {
                QueryEvent.validateJSON(item);
            };
        }

        return true;
    }


}

QueryEventLog.RequiredProperties = ["timestamp", "events"];

/**
 * @member {Number} timestamp
 */
QueryEventLog.prototype['timestamp'] = undefined;

/**
 * @member {Array.<module:model/QueryEvent>} events
 */
QueryEventLog.prototype['events'] = undefined;






export default QueryEventLog;

