/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiClientAnswer from './ApiClientAnswer';

/**
 * The RankedAnswer model module.
 * @module model/RankedAnswer
 * @version 2.0.0-RC4
 */
class RankedAnswer {
    /**
     * Constructs a new <code>RankedAnswer</code>.
     * @alias module:model/RankedAnswer
     * @param answer {module:model/ApiClientAnswer} 
     */
    constructor(answer) { 
        
        RankedAnswer.initialize(this, answer);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, answer) { 
        obj['answer'] = answer;
    }

    /**
     * Constructs a <code>RankedAnswer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RankedAnswer} obj Optional instance to populate.
     * @return {module:model/RankedAnswer} The populated <code>RankedAnswer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RankedAnswer();

            if (data.hasOwnProperty('answer')) {
                obj['answer'] = ApiClientAnswer.constructFromObject(data['answer']);
            }
            if (data.hasOwnProperty('rank')) {
                obj['rank'] = ApiClient.convertToType(data['rank'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RankedAnswer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RankedAnswer</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RankedAnswer.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `answer`
        if (data['answer']) { // data not null
          ApiClientAnswer.validateJSON(data['answer']);
        }

        return true;
    }


}

RankedAnswer.RequiredProperties = ["answer"];

/**
 * @member {module:model/ApiClientAnswer} answer
 */
RankedAnswer.prototype['answer'] = undefined;

/**
 * @member {Number} rank
 */
RankedAnswer.prototype['rank'] = undefined;






export default RankedAnswer;

