/**
 * DRES Client API
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * The version of the OpenAPI document: 2.0.0-RC4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiVerdictStatus from './ApiVerdictStatus';

/**
 * The SuccessfulSubmissionsStatus model module.
 * @module model/SuccessfulSubmissionsStatus
 * @version 2.0.0-RC4
 */
class SuccessfulSubmissionsStatus {
    /**
     * Constructs a new <code>SuccessfulSubmissionsStatus</code>.
     * @alias module:model/SuccessfulSubmissionsStatus
     * @param status {Boolean} 
     * @param submission {module:model/ApiVerdictStatus} 
     * @param description {String} 
     */
    constructor(status, submission, description) { 
        
        SuccessfulSubmissionsStatus.initialize(this, status, submission, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status, submission, description) { 
        obj['status'] = status;
        obj['submission'] = submission;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>SuccessfulSubmissionsStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SuccessfulSubmissionsStatus} obj Optional instance to populate.
     * @return {module:model/SuccessfulSubmissionsStatus} The populated <code>SuccessfulSubmissionsStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SuccessfulSubmissionsStatus();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Boolean');
            }
            if (data.hasOwnProperty('submission')) {
                obj['submission'] = ApiVerdictStatus.constructFromObject(data['submission']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SuccessfulSubmissionsStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SuccessfulSubmissionsStatus</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SuccessfulSubmissionsStatus.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

SuccessfulSubmissionsStatus.RequiredProperties = ["status", "submission", "description"];

/**
 * @member {Boolean} status
 */
SuccessfulSubmissionsStatus.prototype['status'] = undefined;

/**
 * @member {module:model/ApiVerdictStatus} submission
 */
SuccessfulSubmissionsStatus.prototype['submission'] = undefined;

/**
 * @member {String} description
 */
SuccessfulSubmissionsStatus.prototype['description'] = undefined;






export default SuccessfulSubmissionsStatus;

